<?php
namespace AIVisibilityScanner\Report;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use AIVisibilityScanner\Report\Report_Builder;

/**
 * Handles HTML report rendering for browser print & PDF exporting.
 */
class PDF_Exporter {

	/**
	 * Render HTML document formatted for PDF printing.
	 *
	 * @param int $scan_id
	 */
	public function render_pdf_html( int $scan_id ) {
		$report = Report_Builder::get_report( $scan_id );

		if ( ! $report ) {
			wp_die( esc_html__( 'Report not found.', 'ai-visibility-scanner' ) );
		}

		?>
		<!DOCTYPE html>
		<html>
		<head>
			<meta charset="utf-8">
			<title><?php printf( esc_html__( 'AI Visibility Audit Report — %s', 'ai-visibility-scanner' ), esc_html( $report['site_url'] ) ); ?></title>
			<style>
				body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1e1e1e; line-height: 1.5; padding: 20px; }
				.header { border-bottom: 2px solid #2271b1; padding-bottom: 15px; margin-bottom: 25px; }
				.score-box { background: #f0f6fc; border-left: 4px solid #2271b1; padding: 15px; margin-bottom: 20px; }
				.score-title { font-size: 24px; font-weight: bold; }
				table { width: 100%; border-collapse: collapse; margin-top: 15px; }
				th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
				th { background-color: #f6f7f7; }
				.footer { margin-top: 30px; text-align: center; font-size: 11px; color: #666; }
			</style>
		</head>
		<body>
			<div class="header">
				<h1><?php esc_html_e( 'AI Visibility Scanner Audit Report', 'ai-visibility-scanner' ); ?></h1>
				<p>Site: <?php echo esc_html( $report['site_url'] ); ?> | Date: <?php echo esc_html( $report['completed_at'] ); ?></p>
			</div>

			<div class="score-box">
				<div class="score-title">Composite Score: <?php echo esc_html( $report['composite_score'] ); ?> / 100</div>
				<p>Crawlability: <?php echo esc_html( $report['subscores']['crawlability'] ); ?>/100 | Schema: <?php echo esc_html( $report['subscores']['schema'] ); ?>/100 | Content: <?php echo esc_html( $report['subscores']['content'] ); ?>/100 | Experience: <?php echo esc_html( $report['subscores']['experience'] ); ?>/100</p>
			</div>

			<h2>Prioritized Fix Recommendations</h2>
			<table>
				<thead>
					<tr>
						<th>Check</th>
						<th>Page URL</th>
						<th>Result</th>
						<th>Fix Recommendation</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ( $report['prioritized_fixes'] as $fix ) : ?>
						<tr>
							<td><strong><?php echo esc_html( $fix->check_slug ); ?></strong></td>
							<td><?php echo esc_html( $fix->page_url ); ?></td>
							<td><?php echo esc_html( strtoupper( $fix->result ) ); ?></td>
							<td><?php echo esc_html( $fix->fix_hint ); ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>

			<div class="footer">
				Generated by AI Visibility Scanner | Developed by <a href="https://nexvistech.com" target="_blank">NexVis Technologies</a> &amp; <a href="https://github.com/mudassarijaz" target="_blank">Mudassar Ijaz</a>
			</div>
		</body>
		</html>
		<?php
	}
}
