<?php
namespace AIVisibilityScanner\Scanner;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Classifies HTTP response / WP_Error into structured error_type enum values.
 */
class Error_Classifier {

	/**
	 * Classify fetch result.
	 *
	 * @param int|null                $status_code HTTP response code or null
	 * @param array|\WP_Error         $response Raw response or WP_Error object
	 * @param string                  $body_snippet Raw body snippet (~2000 chars)
	 * @param array                   $response_headers Normalized array of response headers
	 * @return string Error type enum value
	 */
	public static function classify( $status_code, $response, string $body_snippet = '', array $response_headers = array() ): string {
		if ( is_wp_error( $response ) ) {
			return self::classify_wp_error( $response );
		}

		$headers_lower = array();
		foreach ( $response_headers as $k => $v ) {
			$headers_lower[ strtolower( (string) $k ) ] = is_array( $v ) ? implode( ', ', $v ) : (string) $v;
		}

		// 1. Cloudflare challenge sniffing
		if ( self::is_cloudflare_challenge( $status_code, $body_snippet, $headers_lower ) ) {
			return 'cloudflare_challenge';
		}

		// 2. WAF block sniffing
		if ( self::is_waf_block( $status_code, $body_snippet, $headers_lower ) ) {
			return 'waf_block_suspected';
		}

		// 3. HTTP status classification
		if ( null !== $status_code && $status_code >= 200 && $status_code < 300 ) {
			return 'none';
		}

		if ( null !== $status_code && ( $status_code < 200 || $status_code >= 300 ) ) {
			return 'http_error';
		}

		return 'unknown';
	}

	/**
	 * Classify WP_Error instances.
	 */
	private static function classify_wp_error( \WP_Error $error ): string {
		$code    = strtolower( (string) $error->get_error_code() );
		$message = strtolower( (string) $error->get_error_message() );

		if ( strpos( $message, 'timed out' ) !== false || strpos( $message, 'timeout' ) !== false || strpos( $code, 'timeout' ) !== false ) {
			return 'timeout';
		}

		if ( strpos( $message, 'could not resolve host' ) !== false || strpos( $message, 'name resolution' ) !== false || strpos( $message, 'dns' ) !== false ) {
			return 'dns_failure';
		}

		if ( strpos( $message, 'connection refused' ) !== false || strpos( $message, 'failed to connect' ) !== false ) {
			return 'connection_refused';
		}

		if ( strpos( $message, 'ssl' ) !== false || strpos( $message, 'certificate' ) !== false || strpos( $message, 'tls' ) !== false ) {
			return 'ssl_error';
		}

		return 'unknown';
	}

	/**
	 * Detect Cloudflare challenge pages.
	 */
	private static function is_cloudflare_challenge( $status_code, string $body, array $headers ): bool {
		if ( isset( $headers['cf-mitigated'] ) && 'challenge' === strtolower( $headers['cf-mitigated'] ) ) {
			return true;
		}

		$cf_markers = array(
			'just a moment...',
			'checking your browser',
			'enable javascript and cookies to continue',
			'cloudflare ray id:',
			'attention required! | cloudflare',
			'cf-browser-verification',
			'turnstile',
		);

		$body_lower = strtolower( $body );
		foreach ( $cf_markers as $marker ) {
			if ( strpos( $body_lower, $marker ) !== false ) {
				return true;
			}
		}

		if ( 503 === (int) $status_code && isset( $headers['cf-ray'] ) && strpos( $body_lower, 'cloudflare' ) !== false ) {
			return true;
		}

		return false;
	}

	/**
	 * Detect suspected WAF blocks.
	 */
	private static function is_waf_block( $status_code, string $body, array $headers ): bool {
		$code = (int) $status_code;
		if ( 403 !== $code && 406 !== $code && 429 !== $code && 500 !== $code ) {
			return false;
		}

		$waf_markers = array(
			'wordfence',
			'generated by wordfence',
			'sucuri website firewall',
			'access denied - sucuri',
			'403 forbidden - mod_security',
			'mod_security',
			'ithemes security',
			'solid security',
			'all in one wp security',
			'blocked by firewall',
			'security check failed',
			'web application firewall',
			'stackpath',
			'incapsula',
			'fortinet',
			'barracuda',
		);

		$body_lower = strtolower( $body );
		foreach ( $waf_markers as $marker ) {
			if ( strpos( $body_lower, $marker ) !== false ) {
				return true;
			}
		}

		return false;
	}
}
